Get compiler version. Set flags for readline when gcc >= 14

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,6 +18,30 @@ Usage() {
   echo ""
 }
 # ------------------------------------------------------------------------------
+
+# Check compiler version.
+CheckCompilerVersion() {
+  c_compiler=$1
+  basecc=`basename $c_compiler`
+  # Use -v
+  cc_version=`$c_compiler -v 2>&1 | grep -E "$basecc |[vV]ersion " \
+                  | sed -e 's/Open64//' -e 's/(.*)//' -e 's/^[a-zA-Z :]* //' -e 's/ .*//'`
+  if [ -z "$cc_version" ] ; then
+     echo "Error: $c_compiler is not well formed or produces unusual version details!"
+     echo "       Check for a CC environment variable."
+     exit 1
+  else
+     echo "  The version of $c_compiler is $cc_version"
+  fi
+  # use '.' as only field delimiter.
+  cc_version=`echo $cc_version | sed -e 's/-/./'`
+  cc_version_major=`echo $cc_version | cut -d'.' -f1`
+  cc_version_minor=`echo $cc_version | cut -d'.' -f2`
+  cc_version_patch=`echo $cc_version | cut -d'.' -f3`
+  #echo "DEBUG: $cc_version $cc_version_major $cc_version_minor $cc_version_patch"
+  #exit 1 # DEBUG
+} 
+
 # If arg is Key=Value, separate into Key and Value
 ParseArg() {
   KEY=`echo "$1" | awk 'BEGIN{FS = "=";}{print $1;}'`
@@ -162,6 +186,7 @@ while [[ ! -z $1 ]] ; do
   shift
 done
 
+
 # Determine compile flags
 case "$COMPILER" in
     "g++" )
@@ -208,6 +233,9 @@ if [[ $USECRAY -eq 1 ]] ; then
   CC=cc
 fi
 
+# Compiler version
+CheckCompilerVersion $CC
+
 # Remove optimizations
 if [[ $NO_OPT -eq 1 ]] ; then
   OPTFLAGS=""
@@ -227,7 +255,15 @@ fi
 INCLUDE="$INCLUDE -I../external -I../external/readline"
 
 # Set up compiler flags
-CXXFLAGS="$DBG_FLAG $OPTFLAGS $LFS $INCLUDE"
+CXXFLAGS="$DBG_FLAG $OPTFLAGS $LFS $INCLUDE $CXXFLAGS"
+CFLAGS="$DBG_FLAG $OPTFLAGS $LFS $INCLUDE $CFLAGS"
+
+# Set version-specific flags
+if [ "$CC" = 'gcc' -a $cc_version_major -ge 14 ] ; then
+  # Needed for readline with gcc >= 14
+  CFLAGS="$CFLAGS -D_DEFAULT_SOURCE -D_XOPEN_SOURCE"
+fi
+
 
 # Test compilers
 TestCompile
@@ -249,6 +285,7 @@ cat > config.h <<EOF
 
 CXX=$CXX
 CXXFLAGS=$CXXFLAGS
+CFLAGS=$CFLAGS
 CC=$CC
 DIRECTIVES=$DIRECTIVES
 LDFLAGS=$LDFLAGS
